CREATE DATABASE IF NOT EXISTS `testmvc` ;
-- create user
CREATE USER 'usermvc'@'localhost' IDENTIFIED BY 'umvc';
GRANT ALL ON testmvc . * TO 'usermvc'@'localhost';
USE `testmvc` ;
CREATE TABLE USER_DETAILS(
USERNAME VARCHAR( 10 ) NOT NULL ,
PASSWORD VARCHAR( 32 ) NOT NULL ,
PRIMARY KEY ( USERNAME )
);
CREATE TABLE USER_AUTH(
USERNAME VARCHAR( 10 ) NOT NULL ,
AUTHORITY VARCHAR( 10 ) NOT NULL ,
FOREIGN KEY ( USERNAME ) REFERENCES USER_DETAILS( USERNAME )
);
); 